dist: xenial
language: python
python:
- '3.8'
install:
- pip install coveralls
- pip install -r requirements.txt
script:
- coverage run --source=./ setup.py test
# - coveralls
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: G+e4BVZLSARuBT5HtzxGQ6dGrIysqt1i9+DuopsKMTa2ayEYR1OcWjq9VhZCe3uMD68eJhMlT6Anh/A00fuAtR3l0QZsIjOtdrxjRxif22PKi6TkqVYU8EVTpCgnpF2pwMKxyXR85zmmkGmX0bbf/TjzzEZFA3nt/R34LUvZGOYsULwF4d501TxSQKdyNfHbYpgbRO5MzhQkdhV9S1Zlagx6eXXciN2cwq8Yw/NYZK3mrAsa6zsDJ9MunL21bFDNHSJH5CsqjEnwS4lYjjzCAsE+Zw4w9Aak+WJfosqx3DZOFUI6M+Svrnmx+5RUgt0XkvuU4xtGajfZeFZmlXbhSGsvi1yVPm79Irv9098YK/L8wsTGeTEB3mTa+xbwecZTqfTpX886M1PneI0IOlpBSlEFEHP+byuq+LtvapqrTx76efAhRgWqfWZHFIHO6bWoocQ8t8N154Fa9ovffQLPbeXoxeFpv9c7Tyaasr+/n5Vh8qTP8HG2PaJ2jP2qTuLTNsyvO5gmUFDZfPk8Iw/pFHE28dYARoRzDLybQF4I0323qWrbyeDrC6Tf7YJiSV+hlB0y7Ug2yDTekvitmbxbeCSZOOeQJ4JiHn6Le12qcUSaJZQKcEasUL5lNNXqDc0CLVA237O3AyW1DrvaNyeI/BK/CQ81BTUI7lxbNw6AXVc=
  on:
    tags: true
